project:
  type: website
  output-dir: _site
  resources:
    - assets/
    - services.html
    - contact.html
    - CNAME
  render:
    - "*.qmd"
    - "!bio.md"
    - "!services-detail.md"

website:
  title: "Ken Moore Solutions"
  navbar:
    right:
      - href: index.html#solutions
        text: "Solutions"
      - href: index.html#works
        text: "Works"
      - text: "Learn"
        menu:
          - href: tutorials.qmd
            text: All Tutorials
          - href: tut-01-first-order-positive-feedback.qmd
            text: "1: Positive Feedback"
          - href: tut-02-first-order-positive-feedback-behavior.qmd
            text: "2: Sensitivity Analysis"
          - href: tut-03-first-order-negative-feedback.qmd
            text: "3: Negative Feedback"
          - href: tut-04-closing-the-gap.qmd
            text: "4: Closing the Gap"
          - href: tut-05-s-shaped-growth.qmd
            text: "5: S-Shaped Growth"
          - href: tut-06-epidemic-sis.qmd
            text: "6: SIS Epidemic"
          - href: tut-07-oscillation-pendulum.qmd
            text: "7: Oscillation"
          - href: tut-08-damped-oscillations.qmd
            text: "8: Damped Oscillations"
      - href: index.html#about
        text: "About"
      - href: contact.html
        text: "Contact"

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    number-sections: false
    highlight-style: tango
